# Default initial positions for rm_description's ros2_control fake system

initial_positions:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
  joint_gripper_left: 0.0
  joint_gripper_right: 0.0